### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MaxSally** [dlshriver/DNNV#29]
Dear,

I encountered this problem while doing `./manage.sh init`

```
  Downloading tensorflow-2.2.2-cp37-cp37m-manylinux2010_x86_64.whl (516.2 MB)
     |████████████████████████████████| 516.2 MB 16.7 MB/s eta 0:00:01Traceback (most recent call last):
  File "DNNV/.venv/bin/flit", line 8, in <module>
    sys.exit(main())
  File "DNNV/.venv/lib/python3.7/site-packages/flit/__init__.py", line 172, in main
    pth=args.pth_file).install()
  File "DNNV/.venv/lib/python3.7/site-packages/flit/install.py", line 413, in install
    self.install_directly()
  File "DNNV/.venv/lib/python3.7/site-packages/flit/install.py", line 298, in install_directly
    self.install_requirements()
  File "DNNV/.venv/lib/python3.7/site-packages/flit/install.py", line 252, in install_requirements
    check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['DNNV/.venv/bin/python', '-m', 'pip', 'install', '-r', '/tmp/tmpyu8k0ec7requirements.txt']' died with <Signals.SIGKILL: 9>.

```
What should I do to fix it? Other libraries are installed successfully.

Thank you for your help. Have a great day. 

Best regards,
Max Nguyen

**Comment by MaxSally** [comment]
I have successfully installed it on a separate server. It may be due to a local configuration. If you have any possible solution, please let me know.
