### ISSUE TITLE
Docker installation error

### ISSUE THREAD

**Issue by LebronX** [dlshriver/DNNV#43]
Hi,

When I try to use docker installation, it report error:
```
=> ERROR [34/36] RUN source .env.d/openenv.sh && python tests/artifacts/build_artifacts.py                                               0.4s
------
 > [34/36] RUN source .env.d/openenv.sh && python tests/artifacts/build_artifacts.py:
#38 0.378 Traceback (most recent call last):
#38 0.378   File "tests/artifacts/build_artifacts.py", line 6, in <module>
#38 0.378     import torch
#38 0.378 ModuleNotFoundError: No module named 'torch'
------
executor failed running [/bin/bash -c source .env.d/openenv.sh && python tests/artifacts/build_artifacts.py]: exit code: 1
```

Thanks

**Comment by dlshriver** [comment]
Hi @LebronX , thank you for your interest in DNNV. I have not been able to reproduce the issue. From the snippet you posted, it appears that pytorch was not installed correctly, but the cause is not clear. Could you try running the build again with the `--progress=plain` option and saving all of the output to a file? Something like: 
`docker build --progress=plain -t dlshriver/dnnv . 2>&1 | tee dockerbuild.log` 
This should provide more evidence to help identify where the failure is occurring.

**Comment by LebronX** [comment]
[dockerbuild.log](https://github.com/dlshriver/DNNV/files/6553184/dockerbuild.log)

As attached

**Comment by dlshriver** [comment]
Thank you. Could you also run it with the `--no-cache` option. It looks like the build re-used all of the cached steps leading up to the error so there is no build information.

**Comment by LebronX** [comment]
[dockerbuild.log](https://github.com/dlshriver/DNNV/files/6553704/dockerbuild.log)

Sure. As attached.

**Comment by dlshriver** [comment]
It looks like the pip installation of torch actually fails in step 32 without causing the build to fail. I've updated the `manage.sh` script so that hopefully the docker build will fail at the correct step, but I'm not sure why the pip installation is failing. My best guess right now is that the download is timing out, but I'm not sure of a good way to fix this, especially since I can't reproduce the issue. Does a manual installation (using `./manage.sh init`) work? I'm trying to narrow down whether the issue is docker specific or not.

**Comment by LebronX** [comment]
Yes manual installation works. Is it to do with system? I try docker on macos and manual installation on Linux.

**Comment by dlshriver** [comment]
Possibly, I'll see if I can test it out on macos. What version of docker are you using?

**Comment by LebronX** [comment]
3.3.1

**Comment by LebronX** [comment]
Something weird happens in manual installation as well.. I try to use neurify and the following error happens. I have also try to remove DNNV, and reinstall the virutal enviroment.

```
$ python -m dnnv property.prop --network N network.onnx --neurify
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "DNNV/dnnv/__init__.py", line 5, in <module>
    from .nn import Operation, OperationVisitor, OperationTransformer
  File "DNNV/dnnv/nn/__init__.py", line 8, in <module>
    from .graph import OperationGraph
  File "DNNV/dnnv/nn/graph.py", line 6, in <module>
    from .operations import Input, Operation
  File "DNNV/dnnv/nn/operations/__init__.py", line 1, in <module>
    from .base import *
  File "DNNV/dnnv/nn/operations/base.py", line 9, in <module>
    from ..utils import ONNX_TO_NUMPY_DTYPE
  File "DNNV/dnnv/nn/utils.py", line 3, in <module>
    import tensorflow.compat.v1 as tf
  File "DNNV/.venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 35, in <module>
    import logging as _logging
  File "DNNV/dnnv/logging/__init__.py", line 7, in <module>
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'
```

**Comment by dlshriver** [comment]
Hmm, that's odd, is the virtual environment active? If so, what is the output of `pip list`?

**Comment by LebronX** [comment]
Yes, I am sure the virtual environment is active. 

Output of `pip list`
```
Traceback (most recent call last):
  File "DNNV/.venv/bin/pip3", line 6, in <module>
    from pip._internal.cli.main import main
  File "DNNV/.venv/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 4, in <module>
    import logging
  File "DNNV/dnnv/logging/__init__.py", line 7, in <module>
    import tensorflow.compat.v1 as tf
  File "DNNV/.venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "DNNV/.venv/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "DNNV/.venv/lib/python3.7/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "DNNV/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 47, in <module>
    from tensorflow.python.eager import context
  File "DNNV/.venv/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 28, in <module>
    from absl import logging
  File "DNNV/.venv/lib/python3.7/site-packages/absl/logging/__init__.py", line 95, in <module>
    from absl.logging import converter
  File "DNNV/.venv/lib/python3.7/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'

```

**Comment by dlshriver** [comment]
It looks like tensorflow wasn't installed for some reason. Running `./manage.sh update` should re-install the python dependencies. If that doesn't work, you may need to remove the virtual environment `rm -rf .venv` and re-initialize it `./manage.sh init`.

**Comment by LebronX** [comment]
Thanks a lot! Now it is fixed!

**Comment by dlshriver** [comment]
Great! I've also added DNNV to docker hub, so instead of having to build the image yourself, you should now be able to do:

```
$ docker pull dlshriver/dnnv
$ docker run --rm -it dlshriver/dnnv
(.venv) dnnv@hostname:~$ python -m dnnv -h
```

Hopefully this will get around the build issue for now.

**Comment by LebronX** [comment]
Thanks David! Maybe the last error of docker, it report error when I try to run an example on Neurify:

```
(.venv) dnnv@008d2d26f599:~/tests/artifacts$ dnnv properties/class_localrobustness_1.py --network N ./networks/mnist_relu_3_50.onnx --neurify
Verifying property:
Forall(x_0, (((x_0 <= (3.0 + randn(1, N[:].input_shape[0][1]).astype(<class 'numpy.float32'>))) & (((randn(1, N[:].input_shape[0][1]).astype(<class 'numpy.float32'>)) - 3.0) <= x_0)) ==> (numpy.argmax(N[:](x_0)) == numpy.argmax(N[:]((randn(1, N[:].input_shape[0][1]).astype(<class 'numpy.float32'>)))))))

Verifying Networks:
N:
Input_0                         : Input([ 1  1 28 28], dtype=float32)
Transpose_0                     : Transpose(Input_0, permutation=[0 2 3 1])
Reshape_0                       : Reshape(Transpose_0, [ -1 784])
Gemm_0                          : Gemm(Reshape_0, ndarray(shape=(50, 784)), ndarray(shape=(50,)))
Relu_0                          : Relu(Gemm_0)
Gemm_1                          : Gemm(Relu_0, ndarray(shape=(50, 50)), ndarray(shape=(50,)))
Relu_1                          : Relu(Gemm_1)
Gemm_2                          : Gemm(Relu_1, ndarray(shape=(10, 50)), ndarray(shape=(10,)))
Relu_2                          : Relu(Gemm_2)

Traceback (most recent call last):
  File "/home/dnnv/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1654, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension must be 2 but is 4 for '{{node transpose}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](transpose/a, transpose/perm)' with input shapes: [1,1], [4].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 72, in wrapped_func
    self._cache[func] = func(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 768, in transpose_func
    result = tf.transpose(x, permutation)
  File "/home/dnnv/.venv/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2122, in transpose
    return transpose_fn(a, perm, name=name)
  File "/home/dnnv/.venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 11181, in transpose
    "Transpose", x=x, perm=perm, name=name)
  File "/home/dnnv/.venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/dnnv/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/home/dnnv/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1817, in __init__
    control_input_ops, op_def)
  File "/home/dnnv/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1657, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension must be 2 but is 4 for '{{node transpose}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](transpose/a, transpose/perm)' with input shapes: [1,1], [4].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dnnv/.venv/bin/dnnv", line 8, in <module>
    sys.exit(_main())
  File "/home/dnnv/dnnv/__main__.py", line 80, in _main
    return exit(main(*cli.parse_args()))
  File "/home/dnnv/dnnv/__main__.py", line 58, in main
    result, cex = verifier.verify(phi, **params)
  File "/home/dnnv/dnnv/verifiers/common/base.py", line 82, in verify
    return cls(phi, **kwargs).run()
  File "/home/dnnv/dnnv/verifiers/common/base.py", line 56, in __init__
    self.property = dnn_property.propagate_constants()
  File "/home/dnnv/dnnv/properties/base.py", line 41, in propagate_constants
    return PropagateConstants().visit(self)
  File "/home/dnnv/dnnv/properties/transformers.py", line 25, in visit
    self.visited[expression] = visitor(expression)
  File "/home/dnnv/dnnv/properties/transformers.py", line 466, in visit_Forall
    expr = self.visit(expression.expression)
  File "/home/dnnv/dnnv/properties/transformers.py", line 25, in visit
    self.visited[expression] = visitor(expression)
  File "/home/dnnv/dnnv/properties/transformers.py", line 551, in visit_Implies
    consequent = self.visit(expression.expr2)
  File "/home/dnnv/dnnv/properties/transformers.py", line 25, in visit
    self.visited[expression] = visitor(expression)
  File "/home/dnnv/dnnv/properties/transformers.py", line 459, in visit_Equal
    expr2 = self.visit(expression.expr2)
  File "/home/dnnv/dnnv/properties/transformers.py", line 25, in visit
    self.visited[expression] = visitor(expression)
  File "/home/dnnv/dnnv/properties/transformers.py", line 473, in visit_FunctionCall
    args = tuple([self.visit(arg) for arg in expression.args])
  File "/home/dnnv/dnnv/properties/transformers.py", line 473, in <listcomp>
    args = tuple([self.visit(arg) for arg in expression.args])
  File "/home/dnnv/dnnv/properties/transformers.py", line 25, in visit
    self.visited[expression] = visitor(expression)
  File "/home/dnnv/dnnv/properties/transformers.py", line 481, in visit_FunctionCall
    result = function.value(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/graph.py", line 166, in __call__
    output = tf_func(*x, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 29, in func
    output = output_func(*inputs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 72, in wrapped_func
    self._cache[func] = func(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 619, in relu_func
    x = _concretize([x_], inputs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 54, in _concretize
    concrete_values.append(variable(*inputs))
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 72, in wrapped_func
    self._cache[func] = func(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 423, in gemm_func
    a, b, c = _concretize([a_, b_, c_], inputs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 54, in _concretize
    concrete_values.append(variable(*inputs))
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 72, in wrapped_func
    self._cache[func] = func(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 619, in relu_func
    x = _concretize([x_], inputs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 54, in _concretize
    concrete_values.append(variable(*inputs))
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 72, in wrapped_func
    self._cache[func] = func(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 423, in gemm_func
    a, b, c = _concretize([a_, b_, c_], inputs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 54, in _concretize
    concrete_values.append(variable(*inputs))
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 72, in wrapped_func
    self._cache[func] = func(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 619, in relu_func
    x = _concretize([x_], inputs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 54, in _concretize
    concrete_values.append(variable(*inputs))
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 72, in wrapped_func
    self._cache[func] = func(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 423, in gemm_func
    a, b, c = _concretize([a_, b_, c_], inputs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 54, in _concretize
    concrete_values.append(variable(*inputs))
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 72, in wrapped_func
    self._cache[func] = func(*args, **kwargs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 635, in reshape_func
    x, shape = _concretize([x_, shape_], inputs)
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 54, in _concretize
    concrete_values.append(variable(*inputs))
  File "/home/dnnv/dnnv/nn/converters/tensorflow.py", line 76, in wrapped_func
    raise TensorflowConverterError(f"{type(e).__name__}: {e.args[0]}")
dnnv.nn.converters.tensorflow.TensorflowConverterError: ValueError: Dimension must be 2 but is 4 for '{{node transpose}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](transpose/a, transpose/perm)' with input shapes: [1,1], [4].
```

**Comment by dlshriver** [comment]
That property was not written for MNIST networks, it is used in our test suite on some small handmade networks. It expects the input to be a flat tensor and has only 2 outputs (which isn't true of MNIST). It can be applied to the particular network that you are using here by setting the environment variable `export INPUT_LAYER=3`, which will verify the network starting after the reshape operation, when the tensor has been flattened. While DNNV will check this property, it is not very meaningful here. This is not a general solution, and is specific to this example.

Also, just to note, this specific specification uses a random point every time, which is probably not what you want in general. The properties in the `tests/artifacts/properties` directory are primarily for testing DNNV and are not necessarily good properties for all networks.

If you want to check some actual MNIST examples, we have converted the ERAN-MNIST benchmark into the DNNV format [here](http://cs.virginia.edu/~dls2fc/eranmnist_benchmark.tar.gz). The properties are local robustness properties.

**Comment by LebronX** [comment]
Thanks a lot for the explanation! Now dnnv works normally!
