### ISSUE TITLE
TypeError: build_identifier() missing 1 required positional argument: 'identifier'

### ISSUE THREAD

**Issue by marti-mcfly** [dlshriver/dnnv#77]
Hi!

when running the following command

`dnnv DNNV/tests/artifacts/properties/localrobustness.py --network N DNNV/tests/artifacts/networks/mnist_relu_3_50.onnx --planet`

I get this error:

```
Traceback (most recent call last):
  File "/home/hmt/test-env/bin/dnnv", line 8, in <module>
    sys.exit(_main())
  File "/home/hmt/test-env/lib/python3.7/site-packages/dnnv/__main__.py", line 115, in _main
    return exit(main(*cli.parse_args()))
  File "/home/hmt/test-env/lib/python3.7/site-packages/dnnv/__main__.py", line 26, in main
    args.property, format=args.prop_format, args=extra_args
  File "/home/hmt/test-env/lib/python3.7/site-packages/dnnv/properties/parser/parse.py", line 14, in parse
    return parse_dsl(path, args)
  File "/home/hmt/test-env/lib/python3.7/site-packages/dnnv/properties/parser/dnnp/parser.py", line 388, in parse
    return parse_str(spec_str, path=path, args=args)
  File "/home/hmt/test-env/lib/python3.7/site-packages/dnnv/properties/parser/dnnp/parser.py", line 375, in parse_str
    exec(code, global_dict)
  File "localrobustness.py", line 9, in <module>
  File "/home/hmt/test-env/lib/python3.7/site-packages/dnnv/properties/expressions/terms/base.py", line 18, in __call__
    identifier = cls.build_identifier(*args, **kwargs)
TypeError: build_identifier() missing 1 required positional argument: 'identifier'
```

I have checked that planet is correctly installed using `dnnv_manage list`. Any pointers would be highly appreciated!

**Comment by dlshriver** [comment]
What is the property specification? You probably need to update to the latest version of DNNV.
